# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0148d822f20f44e26cf37755ece1e1c92da92952642d4366927431b859d42dfc0f7015ea3ce146b1d5d76b9ef8fcf003b4f22417d5c40644f2eff4cbabe058be

test:
  secret_key_base: 191d4efccbae351fc4b24b970bcb05d4ce12994da536d71cb269892b60a5e97b577fed5592a9643b28ae79b018cf2406d1841fa218d9e95b2b7683daaf329d0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
